export const POPULAR_ARTISTS = [
  {
    label: "Hip-Hop and R&B",
    options: [
"21 Savage",
"2Pac",
"A$AP Rocky",
"Big H.A.W.K.",
"Big Moe",
"Bun B",
"Cardi B",
"Chamillionaire",
"Conway The Machine",
"Denzel Curry",
"Doechi",
"Don Toliver",
"Drake",
"Eminem",
"Fat Pat",
"Freddie Gibbs",
"Future",
"Geto Boys",
"GloRilla",
"Gunna",
"Isaiah Rashaad",
"J. Cole",
"JID",
"Jay-Z",
"Jeezy",
"Joey Bada$$",
"Juice WRLD",
"Kanye West",
"Kendrick Lamar",
"Kid Cudi",
"Killer Mike",
"Lil Baby",
"Lil Durk",
"Lil Flip",
"Lil Keke",
"Lil Uzi Vert",
"Lil Wayne",
"Lloyd Banks",
"Lupe Fiasco",
"Maxo Kream",
"Megan Thee Stallion",
"Mac Miller",
"MF Doom",
"Mike Jones",
"Mobb Deep",
"Nas",
"Notorious B.I.G.",
"Outkast",
"Paul Wall",
"Pimp C",
"Playboi Carti",
"Post Malone",
"Pusha T",
"Rick Ross",
"Run The Jewels",
"Scarface",
"Screwed Up Click",
"Shaboozey",
"Slim Thug",
"Snoop Dogg",
"South Park Mexican",
"Trae The Truth",
"Travis Scott",
"Twista",
"Tyler, The Creator",
"UGK",
"Vic Mensa",
"Wu-Tang Clan",
"Youngboy Never Broke Again",
"Z-Ro",
    ]
  },
  {
    label: "Pop",
    options: [
"Amy Winehouse",
  "Aretha Franklin",
"Ariana Grande",
"Bad Bunny",
"Benson Boone",
"Beyonce",
"Billie Eilish",
"Britney Spears",
"Bruno Mars",
"Chappel Roan",
"Charli xcx",
"Dasha",
"Dua Lipa",
"Ed Sheeran",
"Frank Ocean",
"Gracie Abrams",
"Harry Styles",
"Hozier",
"Jessie Murph",
"Justin Bieber",
"Lady Gaga",
"Lana Del Rey",
"Lola Young",
"Lorde",
"Mariah Carey",
"Michael Jackson",
"Miley Cyrus",
"Modest Mouse",
"Olivia Rodrigo",
"Prince",
"Rihanna",
"Sabrina Carpenter",
"sombr",
"SZA",
"Tate McRae",
"Taylor Swift",
"Teddy Swims",
"The Weeknd",
    ]
  },
  {
    label: "Classic Rock",
    options: [
      "AC/DC",
      "Aerosmith",
      "The Allman Brothers Band",
      "The Band",
      "The Beach Boys",
      "The Beatles",
      "Billy Joel",
      "Black Sabbath",
"Blondie",
"Bon Jovi",
"Boston",
"Bruce Springsteen",
"Carlos Santana",
"Chicago",
"The Clash",
"Cream",
"Creedence Clearwater Revival",
"David Bowie",
"Deep Purple",
"Depeche Mode",
"The Doors",
"Eagles",
"Earth, Wind, and Fire",
"Eric Clapton",
"Elton John",
"Fleetwood Mac",
"Foreigner",
"Frank Zappa and the Mothers of Invention",
"Genesis",
"The Grateful Dead",
"Guns N' Roses",
"Heart",
"Iron Maiden",
"Jefferson Airplane",
"Journey",
"Led Zeppelin",
"Lynyrd Skynyrd",
"The Monkees",
"Ozzy Osbourne",
"Pink Floyd",
"Queen",
"R.E.M.",
"Ramones",
"The Rolling Stones",
"Sly and the Family Stone",
"Stevie Ray Vaughan",
"Stevie Wonder",
"Styx",
"The Stooges",
"Tears for Fears",
"Tom Petty",
"Toto",
"U2",
"Van Halen",
"The Velvet Underground",
"Wham!",
"The Who",
"Wings",
    ]
  },
  {
    label: "Rock",
    options: [
"Alice in Chains",
"Artic Monkeys",
"Blink-182",
"Brand New",
"Coldplay",
"The Cure",
"Fall Out Boy",
"Foo Fighters",
"Green Day",
"Incubus",
"The Killers",
"Linkin Park",
"Metallica",
"Neutral Milk Hotel",
"Nine Inch Nails",
"Nirvana",
"No Doubt",
"Oasis",
"Paramore",
"Pearl Jam",
"Radiohead",
"Rage Against The Machine",
"Red Hot Chili Peppers",
"The Shins",
"Smashing Pumpkins",
"Soundgarden",
"The Strokes",
"Taking Back Sunday",
"The White Stripes"
]
},
{
 label: "Country",
 options: [
"Alan Jackson",
"Alex Warren",
"Bailey Zimmerman",
"Blake Shelton",
"Bonnie Tyler",
"Brad Paisley",
"Brett Eldredge",
"Brooks & Dunn",
"The Chicks",
"Chris Isaak",
"Chris Stapleton",
"Cody Johnson",
"Colter Wall",
"Darius Rucker",
"Dolly Parton",
"Dustin Lynch",
"Ella Langley",
"Eric Church",
"Garth Brooks",
"Gene Autrey",
"George Strait",
"Hank Williams",
"Jason Aldean",
"Jason Isbell",
"Johnny Cash",
"Jon Pardi",
"Jordan Davis",
"Kacey Musgraves",
"Keith Urban",
"Kenny Chesney",
"Lainey Wilson",
"Little Big Town",
"Luke Combs",
"Maren Morris",
"Megan Maroney",
"Miranda Lambert",
"Morgan Wallen",
"Riley Green",
"Sam Hunt",
"Shania Twain",
"Sturgill Simpson",
"Thomas Rhett",
"Tim McGraw",
"Toby Keith",
"Whitey Morgan and the 78's",
"Zac Brown Band",
"Zac Bryan"
 ]
},
{
  label: "Folk & Indie",
  options: [
"Bob Dylan",
"Bon Iver",
"Brett Dennen",
"Bright Eyes",
"Carole King",
"Cat Stevens",
"Crosby, Stills, and Nash",
"Dan Fogelberg",
"Gordon Lightfoot",
"Gregory Alan Isakov",
"Iron & Wine",
"James Taylor",
"Jim Croce",
"Joan Baez",
"John Prine",
"Joni Mitchell",
"Leonard Cohen",
"Neil Young",
"Peter, Paul, and Mary",
"Radical Face",
"Simon & Garfunkel",
"The Tallest Man on Earth",
"Townes Van Zandt",
"Woody Guthrie"
  ]
},
{
  label: "Other",
  options: "Other"
}
];

export const POPULAR_GENRES = [
"Alternative",
"Ambient",
"Americana",
"Bluegrass",
"Blues",
"Classical",
"Country",
"Disco",
"Dream Pop",
"Dubstep",
"Electronic",
"Emo",
"Folk",
"Funk",
"Gospel",
"Grime",
"Grunge",
"Hardcore",
"Hip Hop",
"House",
"Indie",
"Jazz",
"Latin",
"Lo-fi",
"Metal",
"New Wave",
"Pop",
"Progressive Rock",
"Psychedelic Rock",
"Punk",
"R&B",
"Reggae",
"Rock",
"Shoegaze",
"Ska",
"Soul",
"Symphonic Rock",
"Synthwave",
"Techno",
"Trap",
  "Other"
];

export const PRICING_PLANS = [
  {
    id: 'free',
    name: 'Open Mic',
    monthlyPrice: 0,
    yearlyPrice: 0,
    credits: 10,
    features: [
      '10 AI songwriter credits',
      'Basic AI companions',
      'Standard lyric suggestions',
      'Community forum access'
    ],
    buttonText: 'Get Started',
    popular: false,
    description: 'Perfect for getting started and exploring your voice.'
  },
  {
    id: 'rising',
    name: 'Rising Artist',
    monthlyPrice: 12,
    yearlyPrice: 120,
    credits: 100,
    features: [
      '100 AI songwriter credits',
      'All standard AI companions',
      'Advanced rhyming brain',
      'Cloud project sync'
    ],
    buttonText: 'Start Rising',
    popular: true,
    description: 'For the consistent creator building a catalog.'
  },
  {
    id: 'headliner',
    name: 'Headliner',
    monthlyPrice: 24,
    yearlyPrice: 240,
    credits: 300,
    features: [
      '300 AI songwriter credits',
      'Exclusive Headliner companions',
      'Beat & chord suggestions',
      'Priority generation speed'
    ],
    buttonText: 'Take the Stage',
    popular: false,
    description: 'For power users who need deep creative tools.'
  },
  {
    id: 'legend',
    name: 'Legend',
    monthlyPrice: 48,
    yearlyPrice: 480,
    credits: 1000,
    features: [
      '1,000 AI songwriter credits/mo',
      'All-access creative pass',
      'Stem splitting & DAW export',
      'Early access to beta tools'
    ],
    buttonText: 'Go Legendary',
    popular: false,
    description: 'The ultimate professional suite for visionaries.'
  }
];
